### ISSUE TITLE
Lesson 3 - Exercise 09

### ISSUE THREAD

**Issue by ghost** [TrainingByPackt/Beginning-AI-Machine-Learning-and-Python#12]
1. Running the following modules modules gives a `NameError: name 'model_selection' is not defined` on line 9
- model_fitting_linear.py
- model_fitting.py
- model_fitting._fib.py

2.  Plots not showing after running the following. Adding `plot.show()` at the end solves this issue
- model_fitting_best_fit_line.py
- model_fitting_np_polyfit.py

**Comment by zsolt-nagy** [comment]
Yes, `2` works well in Jupyter QtConsole, but standalone files are more useful. Thanks for noticing it.
