### ISSUE TITLE
Add Comments to code files

### ISSUE THREAD

**Issue by richardkdbz** [TrainingByPackt/Beginning-AI-Machine-Learning-and-Python#2]
It will be nice to add comments to all the code files so that readers of the code can understand what is going on. At the point there is none at all

**Comment by zsolt-nagy** [comment]
Regarding comments, my point of view is the following:

- where code is not self-documenting, and it is not obvious *after* reading the coursebook or watching the course video, I will add comments for making it more understandable
- however, the source code is not intended to replace the course material, so I will not explain things I explained in the course material. Groups, steps of completing an exercise, or generic comments are added to the source code though.

I will go through all files once more, and check if it is worth adding more comments in any files. Most likely, the answer is yes, so expect a commit to fix this issue.
